### ISSUE TITLE
Libraries should be compiled before distribution

### ISSUE THREAD

**Issue by davidstellini** [ui-router/ng1-to-ng2#5]
Normally, people prevent typescript from compiling their node_modules folder, with good reason.
Unfortunately, your package.json points towards `ng1-to-ng2.ts`, which is a typescript file.

This means that anyone using your library must compile it. Ensure you build your library first, to JS, in a dist folder, and then point your package.json to that file.

The issue may very well be https://github.com/ui-router/ng1-to-ng2/blob/master/.gitignore#L3

**Comment by christopherthielen** [comment]
I'm compiling before publishing to npm.  Are you fetching the git repo or something?

http://npmcdn.com/ui-router-ng1-to-ng2

**Comment by jmlopez-rod** [comment]
A possible issue is that in `package.json` you have

```
"main": "ng1-to-ng2",
```

instead of

```
"main": "ng1-to-ng2.js",
```
I did obtain the compiled js file with npm but somehow typescript was picking up the ts version. The above should fix this problem. Also, is there a way to make it webpack friendly as well? Using your compiled version uses `System` which is not defined when I build. For now I'm having to copy your file into my project to try it out.

**Comment by davidstellini** [comment]
I was unaware that you can throw a different version on npm than on github

https://github.com/ui-router/ng1-to-ng2/pull/7

**Comment by davidstellini** [comment]
Also the System.register() in the compiled JS file is a very valid point, it would be problematic to get it to work with something like webpack.

**Comment by christopherthielen** [comment]
Totally agree, thanks for pointing that out.

**Comment by christopherthielen** [comment]
Version 1.0.10 now points to `main: 'ng1-to-ng2.js'`, and is a UMD bundle using webpack.
